language: java
sudo: enabled

jdk:
  - openjdk11

services:
  - mysql

before_install:
  - "mysql -e 'create database serialize_sample;'"
  - "mysql -e 'use serialize_sample;'"
  - "mysql -e 'insert into person (category, name) values ('human', 'Pereira');'"
  - "mysql -e 'insert into person (category, name) values ('animal', 'Thor');'"

install:
  - ./mvnw clean install
