language: java
sudo: enabled

jdk:
  - openjdk11

services:
  - docker
  
install:
  - "docker run -d --name mysql -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=serialize_sample -p 3306:3306
  
after_install:
  - "mysql -e 'use serialize_sample; insert into person (category, name) values ('human', 'Pereira'); insert into person (category, name) values ('animal', 'Thor');'"
