language: java
sudo: enabled

jdk:
  - openjdk11

services:
  - mysql

before_install:
  - "mysql -e 'create database serialize_sample;'"
  - "mysql -e 'use serialize_sample;'"
  
install:
  - ./mvnw clean install
  
after_install:
  - "mysql -e 'use serialize_sample; insert into person (category, name) values ('human', 'Pereira'); insert into person (category, name) values ('animal', 'Thor');'"
